#ifndef COLOR_H
#define COLOR_H

// Color stuff

#define BLUE_ON_BLACK COLOR_PAIR(1)
#define RED_ON_BLACK COLOR_PAIR(2)
#define GREEN_ON_BLACK COLOR_PAIR(3)
#define YELLOW_ON_BLACK COLOR_PAIR(4)
#define MAGENTA_ON_BLACK COLOR_PAIR(5)
#define CYAN_ON_BLACK COLOR_PAIR(6)
#define WHITE_ON_BLACK COLOR_PAIR(7)
#define YELLOW_ON_BLUE COLOR_PAIR(8)
#define WHITE_ON_BLUE COLOR_PAIR(9)
#define BLACK_ON_YELLOW COLOR_PAIR(10)
#define BLACK_ON_WHITE COLOR_PAIR(11)
#define BLACK_ON_RED COLOR_PAIR(12)
#define BLACK_ON_BLUE COLOR_PAIR(13)
#define BLACK_ON_GREEN COLOR_PAIR(14)

#define MAP_TITLE (color?(BLACK_ON_WHITE):(A_REVERSE))
#define MAP_BORDER (color?(WHITE_ON_BLACK|A_BOLD):(A_BOLD))
#define MAP_SPACE (color?(WHITE_ON_BLACK):(A_NORMAL))
#define MAP_STAR (color?(YELLOW_ON_BLACK|A_BOLD):(A_BOLD))
#define MAP_NEWCO (color?(CYAN_ON_BLACK):(A_NORMAL))
#define MAP_BLACKHOLE (A_NORMAL)
#define CO_A (color?(BLUE_ON_BLACK|A_BOLD):(A_NORMAL))
#define CO_B (color?(GREEN_ON_BLACK):(A_NORMAL))
#define CO_C (color?(YELLOW_ON_BLACK):(A_NORMAL))
#define CO_D (color?(RED_ON_BLACK):(A_NORMAL))
#define CO_E (color?(MAGENTA_ON_BLACK):(A_NORMAL))

#define GENERAL_TITLE (color?(WHITE_ON_BLUE|A_BOLD):(A_REVERSE))
#define GENERAL_TITLE_BLINK (color?(WHITE_ON_BLUE|A_BOLD|A_BLINK):(A_REVERSE|A_BLINK))
#define GENERAL_BORDER (color?(BLUE_ON_BLACK):(A_NORMAL))
#define GENERAL_TEXT (A_NORMAL)

#define COINFO_TITLE (color?(BLACK_ON_GREEN):(A_REVERSE))
#define COINFO_TEXT (A_BOLD)

#define STAND_TITLE (color?(YELLOW_ON_BLUE|A_BOLD):(A_REVERSE))
#define STAND_BORDER (color?(BLUE_ON_BLACK):(A_BOLD))
#define STAND_HEADER (color?(WHITE_ON_BLUE):(A_REVERSE))

#define MORE_COINFO_TITLE (color?(YELLOW_ON_BLUE|A_BOLD):(A_REVERSE))
#define MORE_COINFO_BORDER (color?(BLUE_ON_BLACK):(A_BOLD))
#define MORE_COINFO_HEADER (color?(WHITE_ON_BLUE):(A_REVERSE))

#define QUIT_TITLE (color?(BLACK_ON_RED):(A_REVERSE))
#define QUIT_BORDER (color?(RED_ON_BLACK):(A_BOLD))
#define QUIT_TEXT (color?(YELLOW_ON_BLACK|A_BOLD):(A_NORMAL))

#endif
